### ISSUE TITLE
Migrate to Rust Stable

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#102]
### Goal

It's possible to compile Reactive Graph with rust stable

### Reasons

* Make reproducible builds possible
* Make MSRV possible
* Better efficiency when using binary caches

### Tasks

- [ ] Remove feature flags that require rust nightly
- [ ] Compile `Reactive Graph` successfully with rust stable
- [ ] Use the stable toolchain in GitHub Actions workflows (build with stable, beta and nightly)
- [ ] Determine the msrv version using cargo-msrv and provide the msrv in Cargo.toml

### Current Status

These are the reasons why `Reactive Graph` still needs rust nightly:

#### Use of unstable features

| Feature  | Status | Used for | Action |
| -------- | ------ | -------- | ------ |
| [result_option_inspect](https://github.com/rust-lang/rust/issues/91345) | [Stabilized in 1.76.0](https://github.com/rust-lang/rust/pull/116866) | | ✅ Done |
| [associated_type_bounds](https://github.com/rust-lang/rust/issues/52662) | [Stabilized in 1.79.0](https://github.com/rust-lang/rust/pull/122055) | | ✅ Done |
| [lazy_cell](https://github.com/rust-lang/rust/issues/109736) | [Stabilized in 1.80.0](https://github.com/rust-lang/rust/pull/121377) | | ✅ Done |
| [register_tool](https://github.com/rust-lang/rust/issues/66079) | No progress | Tarpaulin | ✅ Removed |
| [unsized_tuple_coercion](https://github.com/rust-lang/rust/issues/42877) | Unknown | Signals | ✅ Removed |
| [path_file_prefix](https://github.com/rust-lang/rust/issues/86319) | [Stabilization in progress](https://github.com/rust-lang/rust/pull/129114) | Plugin System | ✅ Removed |
| [test](https://doc.rust-lang.org/stable/unstable-book/library-features/test.html) | No Tracking Issue | Benchmark Tests | ✅ Replaced |
| [concat_idents](https://github.com/rust-lang/rust/issues/29599) | [Alternative](https://github.com/rust-lang/rust/issues/124225#issue-2255069330) | Behaviours | ✅ Removed |
| [unboxed_closures<br>fn_traits](https://github.com/rust-lang/rust/issues/29625) | [RFC implemented]() | Properties are Functions<br>`reactive/service/api/src/lib.rs`<br>rust-call | ✅ Feature-Gate |

**Comment by aschaeffer** [comment]
`#![feature(unsized_tuple_coercion)]`

* Implemented DashMap as container for subscribers of `Stream`
* Was able to remove feature flag `unsized_tuple_coercion`

**Comment by aschaeffer** [comment]
### `#![feature(register_tool)]`

* Replaced all usages of `register_tool`
* Whitelisted unexpected cfg `tarpaulin_include`
* Use llvm engine when running code coverage

**Comment by aschaeffer** [comment]
### `#![feature(path_file_prefix)]`

* Removed all usages of `path_file_prefix`
* Inline code from unstable rust of the `file_prefix` method (will be reverted when `path_file_prefix` has been stabilized)

**Comment by aschaeffer** [comment]
#![feature(test)]

* Removed all usages of `test`
* Extracted benchmarks into own `benches/` folders and refactored them to run on top of [criterion](https://crates.io/crates/criterion)

**Comment by aschaeffer** [comment]
### `#![feature(concat_idents)]`

* In https://github.com/rust-lang/rust/pull/128491 the [1.82.0 milestone](https://github.com/rust-lang/rust/milestone/123) was linked.
* The `#![feature(macro_metavar_expr_concat)]` provides a modern alternative to the concat_idents! macro.
* As a first step, we should migrate from `#![feature(concat_idents)]` to `#![feature(macro_metavar_expr_concat)]`
* As a second step, we wait for stabilization of `#![feature(macro_metavar_expr_concat)]` in 1.82.0, to be released at 17 October, 2024

**Comment by aschaeffer** [comment]
### #![feature(unboxed_closures)] and #![feature(fn_traits)]

* Affects only one crate
* Directly access properties as functions
* Detecting nightly or stable using `build.rs` and `rustc_version`
* Dynamically create a feature by rustc channel: `rustc_stable`, `rustc_beta` and `rustc_nightly`
* Conditionally compile with #![feature(unboxed_closures)] and #![feature(fn_traits)] if compiler is nightly (`rustc_nightly`)
* Conditionally implement `FnOnce<(datatype,)>`, `FnMut<(datatype,)>` and `Fn<(datatype,)>` using `rust-call` if compiler is nightly (`rustc_nightly`)
* Compiles on nightly, Test suite passes
* Compiles on stable, Test suite passes
* Obviously the `rust-call` methods haven't been covered by unit tests since no tests failed on stable rust -> we should add unit tests
