### ISSUE TITLE
Control Instance System via CLI

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#112]
Follow up of #81 

### Tasks

- [ ] Client
  - [x] Entity Instances
    - [x] List
    - [x] Get
    - [x] GetByLabel
    - [x] Create
    - [x] Delete
    - [x] Add Component
    - [x] Remove Component
    - [x] Set Property
    - [x] Add Property
    - [x] Remove Property
  - [ ] Relation Instances
    - [x] List
    - [ ] Get
    - [ ] Get Outbound Entity Instance
    - [ ] Get Inbound Entity Instance
    - [ ] Create
    - [ ] Delete
    - [ ] List Components
    - [ ] Add Component
    - [ ] Remove Component
    - [ ] Set Property
    - [ ] Add Property
    - [ ] Remove Property
- [ ] CLI
  - [x] Entity Instances
    - [x] List
    - [x] Get
    - [x] GetByLabel
    - [x] Create
    - [x] Delete
    - [x] List Components
    - [x] Add Component
    - [x] Remove Component
    - [x] List Properties
    - [x] Get Property
    - [x] Set Property
    - [x] Add Property
    - [x] Remove Property
    - [x] Dump as JSON
    - [x] Dump as TOML
  - [ ] Relation Instances
    - [x] List
    - [ ] Get
    - [ ] Get Outbound Entity Instance
    - [ ] Get Inbound Entity Instance
    - [ ] Create
    - [ ] Delete
    - [ ] List Components
    - [ ] Add Component
    - [ ] Remove Component
    - [ ] List Properties
    - [ ] Set Property
    - [ ] Add Property
    - [ ] Remove Property
    - [ ] Dump as JSON
    - [ ] Dump as TOML
