### ISSUE TITLE
Control Flow Types and Flow Instances via CLI

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#122]
Follow up of #81 and #112

### Depends on the Instance System

Flow Types as part of the type system depends on both the type system and the instance system. A Flow Type contains a wrapper entity instance and a list of entity instances and entity types.

### Tasks

- [ ] Client
  - [ ] Flow Types
    - [ ] List
    - [ ] Get
    - [ ] Create
    - [ ] Delete
    - [ ] Set Description
    - [ ] Add Entity Instance
    - [ ] Remove Entity Instance
    - [ ] Add Relation Instance
    - [ ] Remove Relation Instance
    - [ ] Add Component
    - [ ] Remove Component
    - [ ] Add Property
    - [ ] Remove Property
    - [ ] Add Extension
    - [ ] Remove Extension
  - [ ] Flow Instance
    - [ ] List
    - [ ] Get
    - [ ] Create
    - [ ] Delete
    - [ ] List Entity Instances
    - [ ] Add Entity Instance
    - [ ] Remove Entity Instance
    - [ ] List Relation Instances
    - [ ] Add Relation Instance
    - [ ] Remove Relation Instance
    - [ ] List Components (Wrapper)
    - [ ] Add Component (Wrapper)
    - [ ] Remove Component (Wrapper)
    - [ ] List Properties (Wrapper)
    - [ ] Set Property (Wrapper)
    - [ ] Add Property (Wrapper)
    - [ ] Remove Property (Wrapper)
- [ ] CLI
  - [ ] Flow Types
    - [ ] List
    - [ ] Get
    - [ ] Create
    - [ ] Delete
    - [ ] Set Description
    - [ ] Add Entity Instance
    - [ ] Remove Entity Instance
    - [ ] Add Relation Instance
    - [ ] Remove Relation Instance
    - [ ] Add Component
    - [ ] Remove Component
    - [ ] Add Property
    - [ ] Remove Property
    - [ ] Add Extension
    - [ ] Remove Extension
    - [ ] Dump as JSON
    - [ ] Dump as TOML
  - [ ] Flow Instances
    - [ ] List
    - [ ] Get
    - [ ] Create
    - [ ] Delete
    - [ ] Add Entity Instance
    - [ ] Remove Entity Instance
    - [ ] Add Relation Instance
    - [ ] Remove Relation Instance
    - [ ] Add Component
    - [ ] Remove Component
    - [ ] Add Property
    - [ ] Remove Property
    - [ ] Dump as JSON
    - [ ] Dump as TOML
