### ISSUE TITLE
Determine the msrv version using cargo-msrv and provide the msrv in Cargo.toml

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#151]
### Goal

Know what's the minimum rust version to compile successfully.

### Tasks

- [x] Run [cargo-msrv](https://github.com/foresterre/cargo-msrv)
- [x] Provide the `msrv` in `Cargo.toml`
- [x] Check for breaking the msrv policy on every PR

**Comment by aschaeffer** [comment]
```
Check for toolchain '1.80.1-x86_64-unknown-linux-gnu' succeeded
   Finished The MSRV is: 1.80.1
```
