### ISSUE TITLE
JSON-Schema

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#158]
### Goal

The JSON schemas of the type system and instance system are available via GraphQL, Client API and CLI.

### Tasks

- [x] #87
- [ ] GraphQL API: Provide JSON Schemas of the type system and instance system
- [ ] Client API: Query for JSON Schemas of the type system and instance system
- [ ] CLI: Output the JSON Schemas of the type system and instance system
- [ ] CLI: Mark

### Additional Resources

* [VS Code Contribution Point](https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation)
* [JSON Schema Online Editor](https://www.liquid-technologies.com/online-json-to-schema-converter)
