### ISSUE TITLE
 Control plugins via Command Line Interface, Part II

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#165]
The part 2 completes #80 

### Tasks

- [ ] #90
- [ ] Search plugin
    - [ ] GraphQL Test
    - [ ] GraphQL Documentation + Example
    - [ ] Client API Test
- [ ] Get plugin by name
    - [ ] GraphQL Test
    - [ ] GraphQL Documentation + Example
    - [ ] Client API Test
- [ ] Get Dependencies of a plugin
    - [ ] GraphQL Test
    - [ ] Rust Client Test
- [ ] Get Dependents of a plugin
    - [ ] GraphQL Test
    - [ ] Client API Test
- [ ] Start plugin
    - [ ] GraphQL Test
    - [ ] Client API Test
- [ ] Stop plugin
    - [ ] GraphQL Test
    - [ ] Client API Test
- [ ] Restart plugin
    - [ ] GraphQL Test
    - [ ] Client API Test
- [ ] Uninstall plugin
    - [ ] GraphQL Test
    - [ ] Client API
    - [ ] Client API Test
    - [ ] CLI Table Model
    - [ ] CLI Args
    - [ ] CLI Commands
