### ISSUE TITLE
Refactor binaries and CLI

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#181]
### Goals

* Improve extensibility (`tooling`)
* Avoid code duplications

### Tasks

- [x] Modernize
    - [x] [Migrate](https://github.com/rustyhorde/vergen/blob/master/MIGRATING_v8_to_v9.md) to Vergen 9
    - [x] Make use of https://github.com/dtolnay/rustversion
- [x] Move server logic into its own module
    - [x] Split Server CLI Args
    - [x] Split Client CLI Args
    - [x] Flatten subcommands
- [x] Shared
    - [x] Refactor shell-completions generation
    - [x] Refactor man-page generation
    - [x] Refactor markdown help generation
    - [x] Self-Info
- [x] `tooling`
    - [x] Introduce new `tooling` section
    - [x] Feature `tooling`
    - [x] Binary `reactive-graph-tooling`
