### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#183]
### Goal

Provide continuous updated nightly builds.

### Tasks

- [x] Create Release
- [x] Rust Workflow: Create tag `nightly` every time the workflow runs on the `main` branch
- [x] Release Workflow: Trigger on tag nightly
- [x] Release Workflow: Don't create a new release but reuse the release `nightly`
