### ISSUE TITLE
Install standard library plugins

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#225]
By default, Reactive Graph can start without any plugins. This means the possibilities are limited.

### Goal

Install the standard library plugins into the plugin folder of a local instance.

### Acceptance criteria

- [x] After issuing `reactive-graph instances init` the plugins are installed.

### Tasks

- [x] Provide the standard library plugins for download
- [x] Download / update the standard library plugins
- [x] Copy the plugins to the folder `plugins/deploy`

**Comment by aschaeffer** [comment]
The standard library is now available via GitHub Releases:

* https://github.com/reactive-graph/std/releases/tag/nightly
* https://github.com/reactive-graph/std/releases/tag/v0.10.0-alpha-3

This would allow handling plugin installation similar to the [self updater](https://github.com/reactive-graph/reactive-graph/issues/213) which also make use of GitHub Releases:

https://github.com/reactive-graph/reactive-graph/pull/212/files#diff-b3ce9f45aea6f1b573a906eb6b31933ceb77af8ee663b52d61c0327bb11396ef

**Comment by aschaeffer** [comment]
There is still a problem which release to choose. The release of `reactive-graph/reactive-graph` and `reactive-graph/std` must correspond (for example, `reactive-graph/reactive-graph@0.10.0` corresponds with  `reactive-graph/std@0.10.0`). Currently, the latest tag is used, which should be fine for now.
