### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#227]
### Goals

Provide a docker image.

### Acceptance Criteria

- [ ] Lightweight image (based on Alpine Linux)
   > Rust is a compiled language that allows you to export the **final file** to the image in which you are going to run it. Everything is packaged in this compiled file and is executed in the final destination. This makes the final image for languages like Rust, C/C++, or Go very lightweight.
- [ ] Provisioning folder structure
- [ ] The docker image can be downloaded from a registry

### Tasks

- [ ] Create Docker Image
- [ ] Build Docker Image in CI
- [ ] Publish Docker Image to GitHub Releases / https://ghcr.io

### Resources

* [Creating Lightweight Docker Images with Rust](https://medium.com/@pabloperezaradros/creating-lightweight-docker-images-with-rust-0db47cb014a9)
* https://itnext.io/a-practical-guide-to-containerize-your-rust-application-with-docker-77e8a391b4a8
* [Automating Tag Creation, Release, and Docker Image Publish with GitHub Actions ](https://dev.to/natilou/automating-tag-creation-release-and-docker-image-publishing-with-github-actions-49jg)
* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
