### ISSUE TITLE
Rust Edition 2024

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#271]
### Goal

Make Reactive Graph compatible with [Rust Edition 2024](https://blog.rust-lang.org/2024/11/27/Rust-2024-public-testing.html).

### Edition Guide

https://doc.rust-lang.org/nightly/edition-guide/rust-2024/index.html

### Roadmap

| Channel | Date       | Version |
|---------|------------|---------|
| nightly | 2024-11-27 |         |
| beta    | 2025-01-09 |         |
| stable  | 2025-02-02 | 1.85.0  |

### Migration 

- [x] Branch `feature/edition-2024`
- [x] Enable Edition 2024 in `Cargo.toml` (see below)
- [x] Fix `Cargo.toml` (see https://doc.rust-lang.org/nightly/edition-guide/rust-2024/cargo-table-key-names.html)
- [ ] Enable Lints (see below)
- [x] Make code compatible to edition 2024 (by solving the lints)
- [x] Merge source changes into `main` branch (without `edition` and without `lints`)
- [x] Wait for 1.85.0
- [x] Update `Cargo.toml` for edition 2024
- [ ] Merge into `main` branch

#### `Cargo.toml`

```toml
edition = "2024"
resolver = "3"
rustversion = "1.85.0"
```

#### Lints

```rust
#![warn(keyword_idents_2024)]
#![warn(rust_2024_guarded_string_incompatible_syntax)]
#![warn(edition_2024_expr_fragment_specifier)]
#![warn(unsafe_op_in_unsafe_fn)]
#![warn(unsafe_attr_outside_unsafe)]
#![warn(missing_unsafe_on_extern)]
#![warn(tail_expr_drop_order)]
#![warn(if_let_rescope)]
#![warn(rust_2024_prelude_collisions)]
#![warn(deprecated_safe_2024)]
```

### Resources

* https://github.com/rust-lang/rust/pull/133349
* https://rust-lang.github.io/rfcs/3501-edition-2024.html
* https://rust-lang.github.io/rust-project-goals/2024h2/Rust-2024-Edition.html
