### ISSUE TITLE
GraphQL API: Provide JSON-Schemas of the Dynamic Graph

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#276]
### Tasks

- [x] GraphQL API for the Dynamic JSON Schema for Entity Types
- [x] GraphQL API for the Dynamic JSON Schema for Relation Types
- [x] GraphQL API for the Dynamic JSON Schema for Flow Types
