### ISSUE TITLE
Client API: Query for JSON-Schemas of the Dynamic Graph

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#277]
### Tasks

- [x] Query for the Dynamic JSON Schema for Components
- [x] Query for the Dynamic JSON Schema for Entity Types
- [x] Query for the Dynamic JSON Schema for Relation Types
- [x] Query for the Dynamic JSON Schema for Flow Types
