### ISSUE TITLE
Include the unique identifier of the JSON-Schema in each entity of the Dynamic Graph

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#279]
### Tasks

- [x] Include `$id` schema id in the Dynamic JSON Schema of Entity Types (Reactive Entities)
- [x] Include `$id` schema id in the Dynamic JSON Schema of Relation Types (Reactive Relations)
- [x] Include `$id` schema id in the Dynamic JSON Schema of Flow Types (Reactive Flows)
