### ISSUE TITLE
Control Type System via CLI

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#81]
### Tasks

- [x] Client
  - [x] Components
    - [x] List
    - [x] Get
    - [x] Create
    - [x] Delete
    - [x] Set Description
    - [x] Add Property
    - [x] Remove Property
    - [x] Add Extension
    - [x] Remove Extension
  - [x] Entity Types
    - [x] List
    - [x] Get
    - [x] Create
    - [x] Delete
    - [x] Set Description
    - [x] Add Property
    - [x] Remove Property
    - [x] Add Extension
    - [x] Remove Extension
    - [x] Add Component
    - [x] Remove Component
  - [x] Relation Types
    - [x] List
    - [x] Get
    - [x] Create
    - [x] Delete
    - [x] Set Description
    - [x] Add Property
    - [x] Remove Property
    - [x] Add Extension
    - [x] Remove Extension
    - [x] Add Component
    - [x] Remove Component
- [x] CLI
  - [x] Components
    - [x] List
    - [x] Get
    - [x] Create
    - [x] Delete
    - [x] Set Description
    - [x] List Properties
    - [x] Add Property
    - [x] Remove Property
    - [x] List Extensions
    - [x] Add Extension
    - [x] Remove Extension
    - [x] Dump as JSON
    - [x] Dump as TOML
  - [x] Entity Types
    - [x] List
    - [x] Get
    - [x] Create
    - [x] Delete
    - [x] Set Description
    - [x] List Components
    - [x] Add Component
    - [x] Remove Component
    - [x] List Properties
    - [x] Add Property
    - [x] Remove Property
    - [x] List Extensions
    - [x] Add Extension
    - [x] Remove Extension
    - [x] Dump as JSON
    - [x] Dump as TOML
  - [x] Relation Types
    - [x] List
    - [x] Get
    - [x] Create
    - [x] Delete
    - [x] Set Description
    - [x] List Components
    - [x] Add Component
    - [x] Remove Component
    - [x] List Properties
    - [x] Add Property
    - [x] Remove Property
    - [x] List Extensions
    - [x] Add Extension
    - [x] Remove Extension
    - [x] Dump as JSON
    - [x] Dump as TOML

### Flow Types

Flow Types #122 are in a separate issue, because Flow Types depends on the Instance System as well, therefore #112 must be implemented.

**Comment by aschaeffer** [comment]
Implemented by #116, #117, #118 and #119
