### ISSUE TITLE
Document CLI

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/reactive-graph#98]
### Goal

As an administrative user or developer, I want to get information about the command line interface.

### Tasks

- [x] CLI Usage
  - [x] How to use the CLI from a shell
  - [x] How to connect to another runtime via hostname and port parameters
- [x] REPL
  - [x] How to enter the REPL
  - [x] Usage (hints and errors)
  - [x] [Actions](https://github.com/kkawakam/rustyline#actions)
